config/routes.rb
Bookapp::Application.routes.draw do
  
  
  
  match '/search', :to => 'search#index'

	resources :sessions, :only => [:new,:create, :destroy]

  resources :books, :except => [:index]

	resources :users

  
  match '/contact', :to => 'pages#contact'
 
  
  match '/signup', :to => 'users#new'
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  
  root :to => 'pages#home'

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :records
  has_many :owners, :through => :records, :source => :owner  
  # :source parameter which explicitly tells Rails that the source of the owners array is the set of "owner"_id.
  
  
  validates  :title, :presence => true 
  validates  :author_first, :presence => true
  validates  :author_last, :presence => true 
  
  validates  :isbn, :presence => true, 
                    :uniqueness => { :case_sensitive => false}

  attr_accessible :title, :author_first, :author_last, 
                  :description, :year_published, :genre, :isbn, :cover_url



end

app/models/good_reads.rb
require 'goodreads'

class GoodReads

  @client = Goodreads::Client.new(:api_key =>'48CscoZJ4dWudrtBiOlaqg',
                               :api_secret => '35BVnsO0JCY5XKsF1z8MMt2pM9u61gLPke2z0HB9OFo' )
  def self.search(query)

    results = []
    search = @client.search_books(query.to_s)

      if search.results.is_a? Hashie::Mash
        search.results.work.each do |book|
          
          results << book.best_book
        end
      end 
    return results
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  
  attr_accessible :book_id
  
  belongs_to :owner, :class_name => "User" 
  belongs_to :book
  
  validates :owner_id, :presence => true
  validates :book_id,  :presence => true
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  has_many :records, :foreign_key => :owner_id, :dependent => :destroy
  has_many :books, :through => :records, :dependent =>:destroy
  
  
	# allows mass-assignment of the following attributes
	attr_accessible :name, :email, :password, :password_confirmation
	
	#create getters and setters on this raw class
	attr_accessor :password
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name,  :presence => true,
										:length => { :maximum => 50 }
	validates :email, :presence => true,
									  :format => { :with =>email_regex},
									  :uniqueness => { :case_sensitive => false}
									  
	validates :password, :presence => true, 
											 :confirmation => true, 
											 :length => { :within => 6..40 }
											 
	before_save :encrypt_password
	
	# this is the public API into the password machinery
	def has_password?(submitted_password)
		#compare encrypted password with the encrypted version of submitted_password
		encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = User.find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
		#(user && user.has_password?(submitted_password)) ? user : nil
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end
		
	private
	
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
  def new
    @book = Book.new
    @title = "Add a new book"
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    
    @book = current_user.books.create(params[:book])
    if @book.valid?
      flash[:success] = "You've added a new book to your list!"
			redirect_to @book
    else
      render 'new'
    end
      
  end

  def edit
    @title = "Update your book"
    
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      flash[:success] = "Book Updated"
      redirect_to @book
    else
      @title = "Update your book"
      render 'edit'
    end
    
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  	
  end

  def contact
  	@title = "Contact"
  end
  

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def index
    
    @search_results = GoodReads.search(params[:search][:q])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign in"
  end
  
  def create
	  @title = "Sign in"
  	user = User.authenticate(params[:session][:email],
  													 params[:session][:password])
  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination"
  		render 'new'
  	else
  		sign_in user
  		redirect_back_or user
  		
  	end
  end
  
  def destroy
  	sign_out
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
#require 'goodreads'


class UsersController < ApplicationController
  
  before_filter :reject_index, :only => [:index]
  before_filter :authenticate, :only => [:edit, :update, :show]
  before_filter :correct_user, :only => [:edit, :update, :show]
  
  
  def new
  	@user  = User.new
  	@title = "Sign Up"

  end
  
  def show
  	@user = User.find(params[:id])
  	@title = @user.name if @user.valid?
  	@books = @user.books
  	
 	end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to BookSmart!"
			redirect_to @user
		else
			@title = "Sign Up"
			render 'new'
		end
		
	end
	
	def edit
	  @user = User.find(params[:id])
	  @title = "Edit Profile"
	  
	end
	
	
	def update
	 @user = User.find(params[:id])
	 if @user.update_attributes(params[:user])
	  flash[:success] = "Profile Updated"
	  redirect_to @user 
   else
    @title = "Edit Profile"
    render 'edit'
	 end
  end
  
  private
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
  
  def reject_index 
    redirect_to root_path
  end
  
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/good_read_helper.rb
module GoodReadHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end
	
	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
  end
		
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		@current_user ||= user_from_remember_token
	end
	
	def deny_access
	  store_location
	  redirect_to signin_path, :notice => "Please sign in to access this page"
	end
	
	def redirect_back_or(default)
	  redirect_to(session[:return_to] || default)
	  clear_return_to
	end
	
	
	private
	
	def user_from_remember_token
		User.authenticate_with_salt(*remember_token)
	end
	
	def remember_token
		cookies.signed[:remember_token] || [nil, nil]
	end
	
	def signed_in?
		!current_user.nil?
	end
	
	def current_user?(user)
	  user == current_user
	end
	
	def store_location
	  session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
		
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Book#create</h1>
<p>Find me in app/views/book/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Book#edit</h1>
<p>Find me in app/views/book/edit.html.erb</p>

app/views/books/new.html.erb
<h1>Add a new book to your reading list...</h1>
<%= render 'shared/book_details' %>

app/views/books/show.html.erb
<h1>Book#show</h1>
<p>Find me in app/views/book/show.html.erb</p>

app/views/books/update.html.erb
<h1>Book#update</h1>
<p>Find me in app/views/book/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookSmart | <%= @title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Put up the navigation bar here -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="brand">BookSmart</div>
    <ul class="nav">
      
      
      <% if signed_in? %>
        <li><%= link_to "My Books", user_path(current_user)  %></li>
      	<li><%= link_to "Account Settings", edit_user_path(current_user)  %></li>
      	<li><%= link_to "Contact", contact_path %></li>
      	<li><%= link_to "Log out", signout_path, :method => :delete %></li>
      	
      <% else %>
        <li> <%= link_to "Home", root_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      	<li><%= link_to "Sign up!", signup_path %></li>
      <% end %>

    </ul>
  </div>
</div>

<div class="container">

	<section>
		<% flash.each do | key, value | %>
			<div class="alert alert-<%=key%>"><%= value %></div>
		<% end %>
	</section>
  <%= yield %>
</div>

<div>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact us, we'd love to hear from you!</h1>
<p>
<a href="https://github.com/bnc119/bookapp">GitHub project page<a>
</p>

app/views/pages/home.html.erb
<h1>Welcome to BookSmart!</h1>
	<p>
	The easy way to manage your personal library.
	
<% if signed_in? %>

<% else %>
	<%= render 'shared/sign_in_form' %>
<% end %>



		
					
					

app/views/search/index.html.erb
<h2><%= pluralize(@search_results.count, "book") %> found!</h2>

<table class="table table-hover">
  <tr>
    <th></th>
    <th>Title</th>
    <th>Author</th>
    <th></th>
  </tr>
  
  <% unless @search_results.empty? %>
    <% @search_results.each  do |b| %>
      <tr>
        <td><%= image_tag b.image_url %></td>
        <td><%= b.title %></td>
        <td><%= b.author.name %></td>
        <td>

          <% @first = b.author.name.split(" ") %>
          <%= form_for(:book, :url=>books_path) do |f| %>
            
            
            <%= hidden_field_tag "book[title]", b.title %>
            <%= hidden_field_tag "book[author_first]", b.author.name.split(" ")[0] %>
            <%= hidden_field_tag "book[author_last]", b.author.name.split(" ")[1] %>
            <%= hidden_field_tag "book[description]", "Imported from GoodReads" %>
            <%= hidden_field_tag "book[cover_url]", b.image_url %>
            <%= hidden_field_tag "book[isbn]", Digest::MD5.hexdigest(rand.to_s) %>

            <input type="submit" class="btn btn-success" value="Add to list">
          <% end %>

        </td>
      </tr>
    <% end %>
  <% end %>
 
</table>
				

app/views/shared/_book_details.html.erb
<div class="row" id="main-content">
	<div class="span8" id="sidebar">
		<div class="well">
			<%= form_for @book do |f| %>
			
				<%= render 'shared/book_error_messages' %>
				
				<div class="controls">
					<%= f.text_field :title, :class=>"text_field", :placeholder => "Title" %>
				</div>
			
				<div class="controls">
					<%= f.text_field :author_last, :class=>"text_field", :placeholder => "Author Last Name"%>
				</div>
				
				<div class="controls">
					<%= f.text_field :author_first, :class=>"text_field", :placeholder => "Author First Name"%>
				</div>
				
				<div class="controls">
					<%= f.text_area :description, :class=>"text_field", :placeholder => "Description"%>
				</div>
				
				<div class="controls">
					<%= f.text_field :year_published, :class=>"text_field", :placeholder => "Year Published"%>
				</div>
				
				<div class="controls">
					<%= f.text_field :genre, :class=>"text_field", :placeholder => "Genre"%>
				</div>
				
				<div class="controls">
					<%= f.text_field :isbn, :class=>"text_field", :placeholder => "ISBN #"%>
				</div>
			
				
				<div class="actions">
					<%= f.submit "Submit" %>
					

					
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_book_error_messages.html.erb
<% if @book.errors.any? %>

	<div class="alert alert-error">
		<h4>Oh, snap.  We found <%= pluralize(@book.errors.count, "error") %> with your book: </h4>
		<p> There were problems with the following fields </p>
		<ul>
		<% @book.errors.full_messages.each do |m| %>
			<li> <%= m %></li>
		<% end %>
		</ul>
	</div>
	

<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

	<div class="alert alert-error">
		<h4>Oh, snap.  We found <%= pluralize(@user.errors.count, "error") %> with your signup: </h4>
		<p> There were problems with the following fields </p>
		<ul>
		<% @user.errors.full_messages.each do |m| %>
			<li> <%= m %></li>
		<% end %>
		</ul>
	</div>
	

<% end %>

app/views/shared/_sign_in_form.html.erb
<!-- Add login widgets -->
<div class="row" id="main-content">
	<div class="span4" id="sidebar">
		<div class="well">
			<%= form_for(:session, :url =>sessions_path) do |f| %>
			
				<legend>Login</legend>
			
				<%= f.text_field :email, :class=>"text_field", :placeholder => "email" %>
				<%= f.password_field :password, :class=>"password", :placeholder => "password" %>
				
				<input type="submit" class=btn btn-primary" value="login">
				<%= link_to "Or Sign up Now!", signup_path %>
				
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_sign_up_form.html.erb
<div class="row" id="main-content">
	<div class="span8" id="sidebar">
		<div class="well">
			<%= form_for @user do |f| %>
			
				<%= render 'shared/error_messages' %>
				
				<div class="controls">
					<%= f.text_field :name, :class=>"text_field", :placeholder => "Name" %>
				</div>
			
				<div class="controls">
					<%= f.text_field :email, :class=>"text_field", :placeholder => "Email"%>
				</div>
			
				<div class="controls">
					<%= f.password_field :password, :class=>"text_field", :placeholder=>"Password" %>
				</div>
			
				<div class="controls">
					<%= f.password_field :password_confirmation, :class=>"text_field", :placeholder=>"Password Confirmation" %>
				</div>
			
				<div class="actions">
					<%= f.submit "Submit" %>
					<%= link_to "Cancel", root_path, :class=>'btn' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Cool, update your profile</h1>
<%= render 'shared/sign_up_form' %>

app/views/users/index.html.erb
<h2>Show all users here</h2>

app/views/users/new.html.erb
<h1>Create a new account in seconds!</h1>
<%= render 'shared/sign_up_form' %>

app/views/users/show.html.erb
<h2><%= pluralize(@user.books.count, "book") %> in My Reading Queue</h2>

<%= @user.name %>
<%= @user.email %>


<%= form_for(:search, :url =>search_path, :method=>:get) do |f| %>

	<legend>Search</legend>

	<%= f.text_field :q, :class=>"text_field", :placeholder => "search by title or author" %>
	<input type="submit" class=btn btn-primary" value="search">
	
<% end %>
			
       

<ul class="thumbnails">
        
  <% unless @books.empty? %>
    <% @books.each do |b| %>

      <li>
        <a href="#"><%= image_tag b.cover_url %></a>
      </li>
      
    <% end %>
  <% end %>
        
</ul>
		
<%= link_to "Add Book!", new_book_path %>